version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
    - 5432:5432
  mosquitto:
    image: trafex/alpine-mosquitto
    ports:
    - 1883:1883

  pytest:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - mosquitto
    command:
      - sh
      - -c
      - pytest -- tests.py

  api:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - postgres
    command:
      - sh
      - -c
      - flask run --host=0.0.0.0

  consumer:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - mosquitto
    command:
      - sh
      - -c
      - python consumer.py
