version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
    - 5432:5432

  pytest:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - postgres
    command:
      - sh
      - -c
      - pytest -- tests.py

  api:
    build: .
    volumes:
      - ./:/app
    depends_on:
      - postgres
    command:
      - sh
      - -c
      - flask run --host=0.0.0.0
